### ISSUE TITLE
Need custom rules for those sites (NSFW)

### ISSUE THREAD

**Issue by Dean-Corso** [hoothin/UserScripts#135]
Hi hoothin,

I found few sites where your script isn't working for 100% and I wanted to create some custom rules to make them work right. Maybe you can check those sites and create some custom rules to check out what I did miss to add.

Webpage 1: https://femdomup.net/lastnews/
So this website is using video thumbnail previews and the previews aren't working anymore starting from page 2. I tried to make a custom rule and adding the command action": 2 but the animations are not playing. My rule for this site is..
```
    {
        "name": "Femdom",
        "url": "^https://femdomup\\.net",
        "pageElement": "BODY > DIV.wrapper > DIV.content > DIV.cat-shortstory >*",
        "action": 2
    }
```
...but its not working and I would like to know why. Just can make it work when I remove the last pageElement "DIV.cat-shortstory" to go more out  like this "pageElement": "BODY > DIV.wrapper > DIV.content  > main >*", and then it works to see the video previews but the pages itself are looking no more correctly etc pretty bad. Just wanna know why and how to make it right.

Webpage 2: https://joi-me.com/lastnews/
This webpage is not showing correctly from page 2. The content of every single article is shown among themselves and no more side by side. Not sure what custom rule to make in this case.

Webpage 3: https://mixfemdomcc.com/lastnews/
Here almost same problem like on webpage 2, the gray-block classes for each entry are just showing the half image and no more complete from page 2.

Maybe you can check those few webpages out and create some working custom rules I can add and try. Maybe you could explain them a little just to know the reasons and how to make it better next time for myself. Thank you.

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "Femdom",
        "url": "^https://femdomup\\.net",
        "pageElement": ".cat-shortstory",
        "action": 2
    }
</pre>
<pre name="pagetual">
    {
        "name": "Handpicked Jerk-Off Instruction (JOI) Videos",
        "url": "^https://joi-me\\.com",
        "action": "1"
    }
</pre>
<pre name="pagetual">
    {
        "name": "Mixfemdomcc",
        "url": "^https://mixfemdomcc\\.com",
        "css": ".gray-block a.highslide_new > img{transform:unset}"
    }
</pre>
That's because you input a incorrect pageElement so that rule didn't effect.
About other site, you should write css like I paste above. or use "action: 1" to get right css

**Comment by Dean-Corso** [comment]
Hi hoothin,

thanks for your answer. So about the first custom rule. This seems to work good in Firefox but not in Brave browser. On first view it seems also to work in Brave but after few pages they are not showing correctly anymore and its showing the page bar a while. Some kind of overlapping etc. Do you have an idea what parameter to use? Some wait time? By the way, so what does this sandbox parameter mean? I see this is not on the Wiki page or here described. Just see it in some of your rules JSON using true or false for sandbox. Maybe you can tell what it means or whether its just a internal command for yourself.

The second one works fine. Just didn't know & try it without any pageElement parameter. The third rule also works fine. So in this case I just need to pick the image and change the image style. Ah ok. I will test this go on. Thanks again for this rules so far.

**Comment by hoothin** [comment]
I think that because your Brave hasn't updated the script to latest.
"sandbox" is used for iframe to run under sandbox so that child iframe won't effect the current page (sth like navigate the current page).

**Comment by Dean-Corso** [comment]
Hi,

so I did update the script to latest version in Brave too but still got same trouble (with femdomup). During scrolling up/down its flashing and I see the bottom area (page bar & footer) for few moments and then it does re-arrange the site etc. Something is going wrong there. I also tried to disable extensions etc but still got same trouble. In case of Firefox I don't have this trouble but I see sometimes its not showing all anymore and I see just the titles of articles first and without showing the thumbnails (only first row).

So I found another website I don't get it shown correctly. The website starting from page 2 is smaller as the first page. I was trying to create this rule...
```
    {
        "name": XFantazy.com",
        "url": "^https://xfantazy\\.com",
        "pageElement": ".MuiGrid-spacing-xs-1",
        "action": "2"
    },
```
...and the thumbnail previews are working but the pages are still smaller and just showing 3 thumbnails now in one line instead of 4. Not sure what css I have to change to make them fit. So what I have to change in this case? Thanks.

**Comment by hoothin** [comment]
Use "body" instead.
Otherwise you need to overwrite the css below. You can do that but I do not recommend it as you must follow the update of site.
``` css
@media (min-width:936px) {
  .MuiGrid-grid-md-auto {
    flex-grow: 0;
    max-width: none;
    flex-basis: auto;
  }
  .MuiGrid-grid-md-true {
    flex-grow: 1;
    max-width: 100%;
    flex-basis: 0;
  }
  .MuiGrid-grid-md-1 {
    flex-grow: 0;
    max-width: 8.333333%;
    flex-basis: 8.333333%;
  }
  .MuiGrid-grid-md-2 {
    flex-grow: 0;
    max-width: 16.666667%;
    flex-basis: 16.666667%;
  }
  .MuiGrid-grid-md-3 {
    flex-grow: 0;
    max-width: 25%;
    flex-basis: 25%;
  }
  .MuiGrid-grid-md-4 {
    flex-grow: 0;
    max-width: 33.333333%;
    flex-basis: 33.333333%;
  }
  .MuiGrid-grid-md-5 {
    flex-grow: 0;
    max-width: 41.666667%;
    flex-basis: 41.666667%;
  }
  .MuiGrid-grid-md-6 {
    flex-grow: 0;
    max-width: 50%;
    flex-basis: 50%;
  }
  .MuiGrid-grid-md-7 {
    flex-grow: 0;
    max-width: 58.333333%;
    flex-basis: 58.333333%;
  }
  .MuiGrid-grid-md-8 {
    flex-grow: 0;
    max-width: 66.666667%;
    flex-basis: 66.666667%;
  }
  .MuiGrid-grid-md-9 {
    flex-grow: 0;
    max-width: 75%;
    flex-basis: 75%;
  }
  .MuiGrid-grid-md-10 {
    flex-grow: 0;
    max-width: 83.333333%;
    flex-basis: 83.333333%;
  }
  .MuiGrid-grid-md-11 {
    flex-grow: 0;
    max-width: 91.666667%;
    flex-basis: 91.666667%;
  }
  .MuiGrid-grid-md-12 {
    flex-grow: 0;
    max-width: 100%;
    flex-basis: 100%;
  }
}
```
